### ISSUE TITLE
Upload the app icons

### ISSUE THREAD

**Issue by ronniedroid** [FossifyOrg/artwork#3]
@naveensingh can you please upload the app Icons to this repo to be easily accessible.

**Comment by naveensingh** [comment]
Yes, I'll upload them soon...

**Comment by naveensingh** [comment]
@ronniedroid https://github.com/FossifyOrg/artwork/tree/main/Icons

All of them are 512x512 and should look okay with a 20-25% corner radius.

I'll add the remaining soon as well...

**Comment by naveensingh** [comment]
Added more icons: https://github.com/FossifyOrg/artwork/commit/70052fe5b12babe6364c7c3a5177f5effb6fa738
